# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.3
      - image: circleci/postgres:11-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: united_women_test
    environment:
      NODE_ENV: test
      PGUSER: circleci
      PGDATABASE: united_women_test
      EXPRESS_SESSION_SECRET: ABCD1234
      DB_USERNAME: circleci

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - run:
          name: Database Setup
          command: |
            npm run db:migrate
            npm run db:seed

      # run tests!
      - run: npm test
        
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}